version: '3.3'

services:
  postfix:
    build:
      context: postfix
    image: pmphan/mailserver-postfix:latest
    container_name: postfix
    hostname: ${HOSTNAME:-mail.phuongmphan.com}
    ports:
      - "25:25"
      - "587:587"
    secrets:
      - cert_file
      - key_file
    environment:
      MASTER_USER: ${MASTER_USER:-contact}
      MASTER_PASS: ${MASTER_PASS}
      VIRTUAL_USER: ${VIRTUAL_USER:-contact@phuongmphan.com}
      DEBUG_PEER_LIST: ${DEBUG_PEER_LIST:-}
      RELAY_HOST: ${RELAY_HOST:-}
      RELAY_USERNAME: ${RELAY_USERNAME:-}
      RELAY_PASSWORD: ${RELAY_PASSWORD:-}
    restart: unless-stopped

  opendkim:
    build:
      context: opendkim
    image: pmphan/mailserver-opendkim:latest
    container_name: opendkim
    volumes:
      - /etc/dkim/keys:/etc/dkim/keys
    environment:
      DKIM_DOMAIN: ${HOSTNAME:-mail.phuongmphan.com}
      DKIM_SELECTOR: ${DKIM_SELECTOR:-papaya}

secrets:
  cert_file:
    file: /etc/letsencrypt/live/mail.phuongmphan.com/fullchain.pem
  key_file:
    file: /etc/letsencrypt/live/mail.phuongmphan.com/privkey.pem
