version: '3.3'

services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postfix
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  dovecot:
    image: pmphan/mailserver-dovecot:latest
    container_name: dovecot
    ports:
      - "993:993"
    secrets:
      - cert_file
      - key_file
      - dh_file
    environment:
      POSTGRES_DB: postfix
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  postfix:
    image: pmphan/mailserver-postfix:latest
    container_name: postfix
    hostname: ${HOSTNAME}
    ports:
      - "25:25"
    secrets:
      - cert_file
      - key_file
    environment:
      POSTGRES_DB: postfix
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      RELAY_HOST: ${RELAY_HOST}
      RELAY_USER: ${RELAY_USER}
      RELAY_PASSWORD: ${RELAY_PASSWORD}
    restart: unless-stopped

  postfixadmin:
    image: pmphan/mailserver-postfixadmin:latest
    container_name: postfixadmin
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - cert_file
      - key_file
    environment:
      HOSTNAME: ${HOSTNAME}
      POSTFIXADMIN_DB_TYPE: pgsql
      POSTFIXADMIN_DB_HOST: postgres
      POSTFIXADMIN_DB_USER: ${DB_USER}
      POSTFIXADMIN_DB_NAME: postfix
      POSTFIXADMIN_DB_PASSWORD: ${DB_PASSWORD}
      POSTFIXADMIN_SETUP_PASSWORD: ${POSTFIXADMIN_PASSWORD}
      POSTFIXADMIN_SMTP_SERVER: postfix
      POSTFIXADMIN_SMTP_PORT: 25
    restart: unless-stopped

  opendkim:
    image: pmphan/mailserver-opendkim:latest
    container_name: opendkim
    volumes:
      - /etc/dkim/keys:/etc/dkim/keys
    environment:
      DKIM_DOMAIN: ${HOSTNAME}
      DKIM_SELECTOR: ${DKIM_SELECTOR}
    restart: unless-stopped

secrets:
  cert_file:
    file: /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem
  key_file:
    file: /etc/letsencrypt/live/${HOSTNAME}/privkey.pem
  dh_file:
    file: /etc/ssl/dh.pem

volumes:
  postgresdata:
    driver: local
