version: '3'

services:
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    ports:
      - "80:80"
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: ssl://mail.phuongmphan.com
      ROUNDCUBEMAIL_DEFAULT_PORT: 993
      ROUNDCUBEMAIL_SMTP_SERVER: tls://mail.phuongmphan.com
