on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: pmphan/mailserver-${{ inputs.image }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.image }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
