name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log into DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: pmphan/postfix

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: postfix
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: mailserver
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
            {
              "name": "postfix",
              "image": {
                "registry_type": "DOCKER_HUB",
                "registry": "pmphan",
                "repository": "postfix",
                "tag": "latest"
            },
          ]'
