name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: [master]
    tags: [v*]

jobs:
  build-and-publish:
    if: ${{ github.event_name == "push" }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: pmphan/postfix

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: postfix
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SCP docker-compose
        uses: appleboy/scp-action@v0.1.10
        with:
          host: ${{ env.MAILSERVER_HOST }}
          port: 22
          username: ${{ secrets.MAILSERVER_USER }}
          key: ${{ secrets.MAILSERVER_KEY }}
          source: docker-compose.yml
          target: /root/mailserver/

      - name: Deploy
        uses: appleboy/ssh-action
        with:
          host: ${{ env.MAILSERVER_HOST }}
          port: 22
          username: ${{ secrets.MAILSERVER_USER }}
          key: ${{ secrets.MAILSERVER_KEY }}
          script: cd /root/mailserver/ && docker-compose up -d
